### ISSUE TITLE
The color depth is only 8bit, how to increase it? and how to open multiple applications at the same time? 

### ISSUE THREAD

**Issue by wuhgit** [Fmstrat/winapps#176]
I use winapps to run affinity photo under Manjaro, but I find that the display color depth is only 8bit, the UI and the image file has a serious color problem. I searched and found nowhere to adjust the display properties. How can I increase these parameters? 

Another question is that if I need to run multiple applications at the same time, the next opened application will prompt the previous user need to log out, how do I solve this?

Thanks!

**Comment by wuhgit** [comment]
ok, after some search, low color depth solved, just add `RDP_FLAGS="/bpp:32"` to `winapps.conf`.

but open multiple applications at the same time still not solved.

**Comment by MattKowalskii** [comment]
You're asking something that winapps fundamentally cannot provide.
Every time you launch a windows application through winapps, you're essentially logging into the kvm instance, and telling it to launch the program in question.
When you try to connect to that same vm by launching another program, you're gonna hit a wall, since the vm is already connected with the first program. 
You would have to setup several instances of kvm to run multiple programs at once, which i don't even know would be possible.

**Comment by wuhgit** [comment]
> You're asking something that winapps fundamentally cannot provide.
> Every time you launch a windows application through winapps, you're essentially logging into a kvm instance, and telling it to launch the program in question.
> When you try to connect to that same vm by launching another program, you're gonna hit a wall, since the vm is already connected with the first program.
> You would have to setup several instances of kvm to run multiple programs at once, which i don't even know could be possible.

Thanks for your explanation
