### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MatusModder** [Fmstrat/winapps#230]
Can I run games and launchers in this vm because many games don't run via wine/proton

**Comment by vchernin** [comment]
You could try, but it won't be a good experience since you will be using software rendering. For games to be playable you need to either pass a GPU to the VM or use something like GVT-g on older Intel CPUs.

Neither of those things are trivial to do, and require some knowlkedge and understanding of the underlying components. I'd recommend visiting [r/VFIO](https://www.reddit.com/r/VFIO/) which is dedicated to running games in virtual machines.

**Comment by MatusModder** [comment]
Thank you and I am closing this question.
