### ISSUE TITLE
Virsh define

### ISSUE THREAD

**Issue by NigamanRPG** [Fmstrat/winapps#92]
![image](https://user-images.githubusercontent.com/52179357/99803784-d2960f00-2b5b-11eb-9d40-9a979b9e361e.png)
What am I doing wrong?

**Comment by Fmstrat** [comment]
Unfortunately that's not a language I know, and since it's an image I can't cut/paste to translate.. My guess is you are running a distro that doesn't work with the provided XML, and you should just configure your own VM in `virt-manager` however you would like. There's another issue with a working XML for Arch if you are using that, too.

Easing VM construction is the next big item on my list.

**Comment by NigamanRPG** [comment]
I use Arch

**Comment by Fmstrat** [comment]
Ahh, I'm deprecating the XML definition, it's too finicky between systems. Instead, there is now a guide for using KVM linked in the README: https://github.com/Fmstrat/winapps/blob/main/docs/KVM.md

Thanks!
